### ISSUE TITLE
Chat username change doesn't work for self

### ISSUE THREAD

**Issue by antont** [playsign/fidemo#31]
I used the new dialog to set my name but also after it the autogenerated name remained in use when showing the messages to me -- the name does change in the user list, but not in the messages:

```
[010:28:07] fidemo-user1 is now known as Toni.
[010:28:26] fidemo-user1: hop
```

I think the same prob was there with the original dialog too.

Also the UI is a bit confusing with the OK & close buttons in the new dialog .. have to press both OK and then the red cross in the top-right corner, right? Should also the OK button close the popup?

**Comment by Stinkfist0** [comment]
Personally don't find the ok button confusing as the dialog is an info/start dialog, not a username setting dialog.

**Comment by antont** [comment]
thanks - about the UI design with the ok & dialog buts here, I guess I was comparing it with the one here:

http://beta.adminotech.com/virtuaalioulu/

here the same button is both for acking the name & closing the dialog (doing login).

really I think 1 clicks required by the user to 'get in' (here: apply name & close the dialog) is better than 2

**Comment by Stinkfist0** [comment]
Maybe the best solution would be to remove the OK button altogether?
